src/DesafioFPF/DesafioFPF.WebApp/Models/ErrorViewModel.cs
using System;

namespace DesafioFPF.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DesafioFPF/DesafioFPF.WebApp/Controllers/DepartamentoController.cs
using DesafioFPF.WebApp.Banco.Entities;
using DesafioFPF.WebApp.Interface;
using DesafioFPF.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioFPF.WebApp.Controllers
{
    public class DepartamentoController : Controller
    {
        IDepartamentoService departamentoService;

        public DepartamentoController(IDepartamentoService _departamentoService)
        {
            departamentoService = _departamentoService;
        }

        public ViewResult Index(string searchString)
        {
            IEnumerable<Rule> depto = departamentoService.GetAllDepartamento();

            if (!String.IsNullOrEmpty(searchString))
            {
                depto = depto.Where(o => o.Name.ToUpper().Contains(searchString.ToUpper()));
            } 

            return View(depto);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Rule depto)
        {
            departamentoService.AddDepartamento(depto);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            Rule depto = departamentoService.GetDepartamentoById(id);
            return View(depto);
        }

        [HttpPost]
        public ActionResult Edit(Rule depto)
        {
            departamentoService.EditDepartamento(depto);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Rule depto = departamentoService.GetDepartamentoById(id);
            return View(depto);
        }

        [HttpPost]
        public ActionResult Delete(Rule depto)
        {
            departamentoService.DeleteDepartamento(depto);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/DesafioFPF/DesafioFPF.WebApp/Controllers/FuncionarioController.cs
using DesafioFPF.WebApp.Banco.Entities;
using DesafioFPF.WebApp.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioFPF.WebApp.Controllers
{
    public class FuncionarioController : Controller
    {
        IFuncionarioService FuncionarioService;
        IDepartamentoService departamentoService;

        public FuncionarioController(IFuncionarioService _FuncionarioService, IDepartamentoService _departamentoService)
        {
            FuncionarioService = _FuncionarioService;
            departamentoService = _departamentoService;
        }

        public ViewResult Index(string searchString)
        {
            IEnumerable<Employee> depto = FuncionarioService.GetAllFuncionario();

            if (!String.IsNullOrEmpty(searchString))
            {
                depto = depto.Where(o => o.Name.ToUpper().Contains(searchString.ToUpper()));
            }

            return View(depto);
        }

        public IActionResult Create()
        {
            Employee func = new Employee();
            CarregarListasComplementares(func);
            return View(func);
        }

        [HttpPost]
        public ActionResult Create(Employee depto)
        {
            FuncionarioService.AddFuncionario(depto);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            Employee depto = FuncionarioService.GetFuncionarioById(id);
            CarregarListasComplementares(depto);
            return View(depto);
        }

        [HttpPost]
        public ActionResult Edit(Employee depto)
        {
            FuncionarioService.EditFuncionario(depto);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Employee depto = FuncionarioService.GetFuncionarioById(id);
            return View(depto);
        }

        [HttpPost]
        public ActionResult Delete(Employee depto)
        {
            FuncionarioService.DeleteFuncionario(depto);
            return RedirectToAction(nameof(Index));
        }

        private void CarregarListasComplementares(Employee itemViewModel)
        {
            List<Rule> depto = departamentoService.CarregaDepartamento();

            itemViewModel.Departamento = depto;
        }
    }
}

src/DesafioFPF/DesafioFPF.WebApp/Controllers/GraficoController.cs
using DesafioFPF.WebApp.Banco.Entities;
using DesafioFPF.WebApp.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioFPF.WebApp.Controllers
{
    public class GraficoController : Controller
    {
        IGraficoService graficoService;

        public GraficoController(IGraficoService _graficoService)
        {
            graficoService = _graficoService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Data()
        {
            List<Employee> depto = graficoService.GetGrafico();

            List<object> obj = new List<object>();
            try
            {                
                foreach (var item in depto)
                {
                    obj.Add(new
                    {
                        Nome = item.Name,
                        Salario = item.Salary
                    });
                }

                ViewBag.Listagem = depto;
            }
            catch (Exception ex)
            {
            }

            return Json(obj);
        }
    }
}

src/DesafioFPF/DesafioFPF.WebApp/Controllers/HomeController.cs
using DesafioFPF.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioFPF.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/DesafioFPF/DesafioFPF.WebApp/Views/Departamento/Create.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Rule

@{
    ViewData["Title"] = "Create";
}

<h1>Departamento</h1>

@*<h4>Rule</h4>*@
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" hidden>
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Nome</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Situação</label>
        <select class="form-control" asp-for="Active" id="Active" name="Active">
            <option value=""></option>
            <option value="A">Ativo</option>
            <option value="I">Inativo</option>
        </select>
    </div>
    <div class="form-group" hidden>
        <label asp-for="CreatedAt" class="control-label"></label>
        <input asp-for="CreatedAt" class="form-control" />
        <span asp-validation-for="CreatedAt" class="text-danger"></span>
    </div>
    <div class="form-group" hidden>
        <label asp-for="ModifiedAt" class="control-label"></label>
        <input asp-for="ModifiedAt" class="form-control" />
        <span asp-validation-for="ModifiedAt" class="text-danger"></span>
    </div>
    <div class="form-group text-right">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <button type="button" class="btn btn-danger" value="Cancel" onclick="history.back();">Cancelar</button>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DesafioFPF/DesafioFPF.WebApp/Views/Departamento/Delete.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Rule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Deseja Excluir ?</h3>
<div>
    <h4>Rule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Departamento/Edit.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Rule

@{
    ViewData["Title"] = "Edit";
}

<h1>Departamento</h1>

@*<h4>Rule</h4>*@
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" hidden>
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Nome</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Situação</label>
        <select class="form-control" asp-for="Active" id="Active" name="Active">
            <option value=""></option>
            <option value="A">Ativo</option>
            <option value="I">Inativo</option>
        </select>
    </div>
    <div class="form-group" hidden>
        <label asp-for="CreatedAt" class="control-label"></label>
        <input asp-for="CreatedAt" class="form-control" />
        <span asp-validation-for="CreatedAt" class="text-danger"></span>
    </div>
    <div class="form-group" hidden>
        <label asp-for="ModifiedAt" class="control-label"></label>
        <input asp-for="ModifiedAt" class="form-control" />
        <span asp-validation-for="ModifiedAt" class="text-danger"></span>
    </div>
    <div class="form-group text-right">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <button type="button" class="btn btn-danger" value="Cancel" onclick="history.back();">Cancelar</button>
    </div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DesafioFPF/DesafioFPF.WebApp/Views/Departamento/Index.cshtml
@model IEnumerable<DesafioFPF.WebApp.Banco.Entities.Rule>

@{
    ViewData["Title"] = "Departamento";
}

<h1>Departamento</h1>

<div class="form-group text-right">
    @*<a asp-action="Create">Create New</a>*@
    <a class="btn btn-success" asp-action="Create" role="button">Novo</a>
</div>
<div class="form-group text-right">
    @using (Html.BeginForm())
    {
        <p>
            Procurar: @Html.TextBox("searchString")
            <input type="submit" name="Busca" />
        </p>
    }
</div>
<div class="form-group">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Modificado em</th>
                <th scope="col">Ativo</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Funcionario/Create.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Funcionário</h1>

@*<h4>Employee</h4>*@
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Nome</label>
        <input asp-for="Name" type="text" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="form-group col">
            <label asp-for="IdRule" class="control-label">Departamento</label>
            <select asp-for="IdRule" class="form-control" id="comboDepto">
                <option disabled selected>-- Selecione --</option>
                @foreach (var depto in Model.Departamento)
                {
                    <option data-Id="@depto.Id" value="@depto.Id">@depto.Name</option>
                }
            </select>
            @*<input asp-for="IdRule" type="text" class="form-control" />*@
            <span asp-validation-for="IdRule" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <label for="exampleFormControlSelect1">Sexo</label>
            <select asp-for="Gender" class="form-control" id="Gender" name="Gender">
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
            </select>
        </div>
        <div class="form-group col">
            <label for="exampleFormControlSelect1">Situação</label>
            <select asp-for="Active" class="form-control" id="Active" name="Active">
                <option value="A">Ativo</option>
                <option value="I">Inativo</option>
            </select>
        </div>
        <div class="form-group col">
            <label asp-for="Salary" class="control-label">Salário</label>
            <input asp-for="Salary" class="form-control" />
            <span asp-validation-for="Salary" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="CreatedAt" class="control-label"></label>
            <input asp-for="CreatedAt" class="form-control" />
            <span asp-validation-for="CreatedAt" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="ModifiedAt" class="control-label"></label>
            <input asp-for="ModifiedAt" class="form-control" />
            <span asp-validation-for="ModifiedAt" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group text-right">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <button type="button" class="btn btn-danger" value="Cancel" onclick="history.back();">Cancelar</button>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DesafioFPF/DesafioFPF.WebApp/Views/Funcionario/Delete.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Deseja excluir ?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdRule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdRule)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Funcionario/Edit.cshtml
@model DesafioFPF.WebApp.Banco.Entities.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Funcionário</h1>

@*<h4>Employee</h4>*@
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" hidden>
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Nome</label>
        <input asp-for="Name" type="text" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="form-group col">
            <label asp-for="IdRule" class="control-label">Departamento</label>
            <select asp-for="IdRule" class="form-control" id="comboDepto">
                <option disabled selected>-- Selecione --</option>
                @foreach (var depto in Model.Departamento)
                {
                    <option data-cd_srv="@depto.Id" value="@depto.Id">@depto.Name</option>
                }
            </select>
            @*<input asp-for="IdRule" type="text" class="form-control" />*@
            <span asp-validation-for="IdRule" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <label for="exampleFormControlSelect1">Sexo</label>
            <select asp-for="Gender" class="form-control" id="Gender" name="Gender">
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
            </select>
        </div>
        <div class="form-group col">
            <label for="exampleFormControlSelect1">Situação</label>
            <select asp-for="Active" class="form-control" id="Active" name="Active">
                <option value="A">Ativo</option>
                <option value="I">Inativo</option>
            </select>
        </div>
        <div class="form-group col">
            <label asp-for="Salary" class="control-label">Salário</label>
            <input asp-for="Salary" class="form-control" />
            <span asp-validation-for="Salary" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="CreatedAt" class="control-label"></label>
            <input asp-for="CreatedAt" class="form-control" />
            <span asp-validation-for="CreatedAt" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="ModifiedAt" class="control-label"></label>
            <input asp-for="ModifiedAt" class="form-control" />
            <span asp-validation-for="ModifiedAt" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group text-right">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <button type="button" class="btn btn-danger" value="Cancel" onclick="history.back();">Cancelar</button>
    </div>
</form>

src/DesafioFPF/DesafioFPF.WebApp/Views/Funcionario/Index.cshtml
@model IEnumerable<DesafioFPF.WebApp.Banco.Entities.Employee>

@{
    ViewData["Title"] = "Funcionários";
}

<h1>Funcionários</h1>

<div class="form-group text-right">
    @*<a asp-action="Create">Create New</a>*@
    <a class="btn btn-success" asp-action="Create" role="button">Novo</a>
</div>
<div class="form-group text-right">
    @using (Html.BeginForm())
    {
        <p>
            Procurar: @Html.TextBox("searchString")
            <input type="submit" name="Busca" />
        </p>
    }
</div>
<div class="form-group">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Sexo</th>
                <th scope="col">Modificado em</th>
                <th scope="col">Ativo</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Grafico/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript"
        src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json',
            url: '@Url.Action("Data","Grafico")',
            success: function (result) {
                google.charts.load('current', { 'packages': ['corechart'] });
                google.charts.setOnLoadCallback(function () {
                    drawChart(result);
                });
            }
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Nome');
            data.addColumn('number', 'Salario');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.nome, obj.salario]);
            });


            data.addRows(dataArray);

            //var pierchart_options = {
            //    title: 'Relação de pesquisas Confirmadas e Canceladas',
            //    width: 500,
            //    height: 400,
            //};
            //var pierchart = new google.visualization.PieChart(document.getElementById('pierchart_div'));
            //pierchart.draw(data, pierchart_options);

            var barchart_options = {
                title: '',
                width: 500,
                height: 400,
                legend: 'none'
            };
            var barchart = new google.visualization.ColumnChart(document.getElementById('barchart_div'));
            barchart.draw(data, barchart_options);
        }
    });
</script>

<div class="container">
    <h1 class="page-header">Total de salários por departamento</h1>
    <table class="columns">
        <tr>
            <td><div id="pierchart_div" style="border: 1px solid #ccc"></div></td>
            <td><div id="barchart_div" style="border: 1px solid #ccc"></div></td>
        </tr>
    </table>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/DesafioFPF/DesafioFPF.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioFPF.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="row">
        <div class="flex-column" style="background-color: black; padding-bottom: 100%;
">
            <a style="color:aliceblue;font-size:30px; padding-left:20px; padding-right:30px;">Cadastros</a>
            <li class="nav-item" style="margin-top: -26px; padding-left: 10px;">
                <a class="nav-link" style="color:aliceblue" href="/">Departamento</a>
                <a class="nav-link" style="color:aliceblue" href="/Funcionario">Funcionários</a>
            </li>
            <a style="color:aliceblue;font-size:30px; padding-left:20px; padding-right:30px;">Relatórios</a>
            <li class="nav-item" style="margin-top: -26px; padding-left: 10px;">
                <a class="nav-link" style="color:aliceblue" href="/Grafico">Total de Salários</a>
            </li>
        </div>
        <div class="form-group col-sm-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DesafioFPF.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
</body>
</html>